# FROM apache/airflow:2.7.3

FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install --upgrade pip && \
pip install --no-cache-dir -r /tmp/requirements.txt

USER root
RUN rm /tmp/requirements.txt